const { callOllamaAPI } = require('./ollamaService');
const { parseAgentJsonResponse } = require('../utils/agentParser');
const { AGENTS } = require('../config/agents');
const {
  getDiagnoserContext,
  getPatcherContext,
  getCommunicatorContext,
  buildDiagnoserRagContext,
  buildPatcherRagContext,
  buildCommunicatorRagContext,
} = require('./ragService');
const { Octokit } = require('@octokit/rest');
const { saveFullIncident } = require('./mongoService');

const octokit = process.env.GITHUB_TOKEN ? new Octokit({ auth: process.env.GITHUB_TOKEN }) : null;

/**
 * Send Slack notification via webhook
 */
async function sendSlackNotification(incident, watcherResult, diagnoserResult, patcherResult, communicatorResult) {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) {
    console.log('Slack webhook URL not configured, skipping notification');
    return { success: false, reason: 'No webhook URL' };
  }

  const severity = watcherResult.severity || 'high';
  const severityEmoji = severity === 'critical' ? ':rotating_light:' : severity === 'high' ? ':warning:' : ':large_yellow_circle:';
  
  const blocks = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: `${severityEmoji} INC-${incident.id} | ${severity.toUpperCase()} | ${incident.component || 'unknown'}`
      }
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*${incident.title}*\n${communicatorResult.slackMessage || communicatorResult.message || 'Incident detected and analyzed'}`
      }
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Root Cause:*\n${diagnoserResult.rootCause || 'Unknown'}` },
        { type: 'mrkdwn', text: `*Fix:*\n${patcherResult.recommendedFix || 'Pending'}` },
        { type: 'mrkdwn', text: `*Type:* ${patcherResult.fixType || 'N/A'}` },
        { type: 'mrkdwn', text: `*Risk:* ${patcherResult.riskLevel || 'N/A'}` },
        { type: 'mrkdwn', text: `*ETA:* ${patcherResult.estimatedTime || 'N/A'}` },
        { type: 'mrkdwn', text: `*Confidence:* ${Math.round((diagnoserResult.confidence || 0) * 100)}%` }
      ]
    },
    {
      type: 'context',
      elements: [
        { type: 'mrkdwn', text: `IncidentMind Autonomous Response | ${new Date().toISOString()}` }
      ]
    }
  ];

  try {
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ blocks })
    });
    if (!response.ok) {
      throw new Error(`Slack webhook failed: ${response.status}`);
    }
    return { success: true };
  } catch (error) {
    console.error('Slack notification failed:', error);
    return { success: false, error: error.message };
  }
}

/**
 * Create GitHub PR for patch
 */
async function createGitHubPR(incident, patcherResult, diagnoserResult) {
  if (!octokit) {
    console.log('GitHub token not configured, skipping PR creation');
    return { success: false, reason: 'No GitHub token' };
  }

  const owner = process.env.GITHUB_OWNER || 'incidentmind-io';
  const repo = process.env.GITHUB_REPO || 'platform-config';
  const branchName = `incidentmind/patch-${incident.id}-${Date.now()}`;
  const baseBranch = process.env.GITHUB_BASE_BRANCH || 'main';

  try {
    // Get base branch SHA
    const { data: baseRef } = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
    const baseSha = baseRef.object.sha;

    // Create new branch
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha
    });

    // Create patch file content
    const patchContent = `# IncidentMind Auto-Patch: INC-${incident.id}

## Incident Details
- **ID**: ${incident.id}
- **Title**: ${incident.title}
- **Component**: ${incident.component}
- **Severity**: ${incident.severity || 'unknown'}
- **Timestamp**: ${new Date().toISOString()}

## Diagnosis
- **Root Cause**: ${diagnoserResult.rootCause}
- **Confidence**: ${Math.round((diagnoserResult.confidence || 0) * 100)}%
- **Contributing Factors**: ${(diagnoserResult.contributingFactors || []).join(', ')}

## Recommended Fix
- **Type**: ${patcherResult.fixType}
- **Description**: ${patcherResult.recommendedFix}
- **Risk Level**: ${patcherResult.riskLevel}
- **Estimated Time**: ${patcherResult.estimatedTime}

## Commands
\`\`\`bash
${(patcherResult.commands || []).join('\n')}
\`\`\`

## Rollback Plan
${patcherResult.rollbackPlan}

---
*Auto-generated by IncidentMind Agent System*
`;

    // Create file
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: `patches/INC-${incident.id}.md`,
      message: `[IncidentMind] Auto-patch: INC-${incident.id} — ${diagnoserResult.rootCause?.slice(0, 50) || 'incident'}`,
      content: Buffer.from(patchContent).toString('base64'),
      branch: branchName
    });

    // Create PR
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: `[IncidentMind] Auto-patch: INC-${incident.id} — ${diagnoserResult.rootCause?.slice(0, 60) || 'incident'}`,
      head: branchName,
      base: baseBranch,
      body: `## Automated Patch for Incident ${incident.id}

**Incident**: ${incident.title}
**Component**: ${incident.component}
**Root Cause**: ${diagnoserResult.rootCause}
**Fix Type**: ${patcherResult.fixType}
**Risk**: ${patcherResult.riskLevel}
**ETA**: ${patcherResult.estimatedTime}

### Commands
\`\`\`bash
${(patcherResult.commands || []).join('\n')}
\`\`\`

### Rollback Plan
${patcherResult.rollbackPlan}

---
*This PR was created automatically by IncidentMind's Patcher agent. Review before merging.*`,
      labels: ['automated-patch', 'incident-response']
    });

    return { success: true, prUrl: pr.html_url, prNumber: pr.number };
  } catch (error) {
    console.error('GitHub PR creation failed:', error);
    return { success: false, error: error.message };
  }
}

/**
 * Pure JS Watcher agent (no LLM) - deterministic threshold detection
 * @param {Object} metrics - System metrics
 * @param {string} component - The affected component name
 * @returns {Object} Anomaly detection result
 */
function runWatcher(metrics, component) {
  const cpuUsage = metrics.cpuUsage ?? metrics.cpu ?? 0;
  const memoryUsage = metrics.memoryUsage ?? metrics.memory ?? 0;
  const errorRate = metrics.errorRate ?? 0;
  const requestLatency = metrics.requestLatency ?? metrics.latency ?? 0;

  const anomalyDetected = cpuUsage > 90 || memoryUsage > 85 || errorRate > 0.1 || requestLatency > 500;
  const confidence = anomalyDetected ? 0.95 : 0.1;
  const description = anomalyDetected
    ? `High CPU usage: ${cpuUsage}%` + (memoryUsage > 85 ? `, Memory: ${memoryUsage}%` : '') + (errorRate > 0.1 ? `, Error rate: ${(errorRate * 100).toFixed(1)}%` : '')
    : 'Normal metrics';
  const severity = anomalyDetected ? 'high' : 'low';
  const affectedComponents = anomalyDetected ? [component || 'api-server'] : [];

  return {
    anomalyDetected,
    confidence,
    description,
    severity,
    affectedComponents
  };
}

/**
 * Runs the agent chain for a given incident.
 * @param {Object} incident - The incident object.
 * @returns {Promise<Object>} Results from each agent in the chain.
 */
async function runAgentChain(incident) {
  console.log(`Starting incident analysis for: ${incident.title}`);

  // Step 1: Orchestrator
  console.log(' About to write agent_start for Orchestrator');
  const orchestratorPrompt = `
    Incident triggered: ${incident.title}
    Description: ${incident.description}
    Metrics: ${JSON.stringify(incident.metrics, null, 2)}

    Determine the appropriate agent sequence and any initial context for handling this incident.
  `;

  const orchestratorResult = await callOllamaAPI(AGENTS.ORCHESTRATOR, orchestratorPrompt);

  // Use the sequence from orchestrator if provided, otherwise default
  const agentSequence = orchestratorResult.sequence || ['Watcher', 'Diagnoser', 'Patcher', 'Communicator'];
  const context = orchestratorResult.context || {};
  const instructions = orchestratorResult.instructions || '';

  // Step 2: Watcher (pure JS - no LLM)
  const watcherResult = runWatcher(incident.metrics, incident.component);

  // If no significant anomaly, we can stop early
  if (!watcherResult.anomalyDetected || watcherResult.confidence < 0.3) {
    return {
      orchestrator: orchestratorResult,
      watcher: watcherResult,
      // We'll set a flag to indicate no further action needed
      status: 'no_action_needed'
    };
  }

  // Step 3 & 4: Run Diagnoser and Patcher in PARALLEL (Promise.all)
  // Prepare Diagnoser prompt
  const { pastIncidents, runbooks: diagnoserRunbooks } = await getDiagnoserContext(
    incident.component || 'unknown',
    watcherResult.description || 'anomaly'
  );
  const diagnoserRagContext = buildDiagnoserRagContext(pastIncidents, diagnoserRunbooks);

  const diagnoserPrompt = `
    Watcher's analysis:
    ${JSON.stringify(watcherResult, null, 2)}

    Original metrics:
    ${JSON.stringify(incident.metrics, null, 2)}

    Incident description: ${incident.description}

    ${diagnoserRagContext}

    Analyze the anomaly context and determine the root cause.
  `;

  // Prepare Patcher prompt (preliminary - based on watcher + RAG, refined after diagnosis)
  const { runbooks: patcherRunbooks, patchCommands } = await getPatcherContext(
    'pending_diagnosis', // placeholder, will be refined
    incident.component || 'service'
  );
  const patcherRagContext = buildPatcherRagContext(patcherRunbooks, patchCommands);

  const preliminaryPatcherPrompt = `
    Watcher's analysis:
    ${JSON.stringify(watcherResult, null, 2)}

    Original metrics:
    ${JSON.stringify(incident.metrics, null, 2)}

    Incident description: ${incident.description}

    ${patcherRagContext}

    Generate a preliminary recommended fix based on the anomaly signals. 
    The final diagnosis will be available shortly to refine this fix.
  `;

  // Run both agents in PARALLEL
  console.log('Running Diagnoser and Patcher in parallel...');
  const [diagnoserResult, preliminaryPatcherResult] = await Promise.all([
    callOllamaAPI(AGENTS.DIAGNOSER, diagnoserPrompt),
    callOllamaAPI(AGENTS.PATCHER, preliminaryPatcherPrompt)
  ]);
  
  diagnoserResult.retrievedContext = { pastIncidents, runbooks: diagnoserRunbooks };
  preliminaryPatcherResult.retrievedContext = { runbooks: patcherRunbooks, patchCommands };

  // Refine Patcher result with actual diagnosis
  const refinedPatcherPrompt = `
    Diagnoser's analysis:
    ${JSON.stringify(diagnoserResult, null, 2)}

    Preliminary fix draft:
    ${JSON.stringify(preliminaryPatcherResult, null, 2)}

    ${patcherRagContext}

    Based on the confirmed diagnosis, refine and finalize the recommended fix.
  `;
  
  const patcherResult = await callOllamaAPI(AGENTS.PATCHER, refinedPatcherPrompt);
  patcherResult.retrievedContext = { runbooks: patcherRunbooks, patchCommands };

  // Step 5: Communicator - with RAG
  const { runbooks: communicatorRunbooks } = await getCommunicatorContext(
    `${incident.title} - ${diagnoserResult.rootCause}`,
    watcherResult.severity || 'high'
  );
  const communicatorRagContext = buildCommunicatorRagContext(communicatorRunbooks);

  const communicatorPrompt = `
    Diagnosis: ${JSON.stringify(diagnoserResult, null, 2)}
    Patch: ${JSON.stringify(patcherResult, null, 2)}

    ${communicatorRagContext}

    Draft a clear, concise message for the team summarizing the incident, diagnosis, and recommended actions.
  `;

  const communicatorResult = await callOllamaAPI(AGENTS.COMMUNICATOR, communicatorPrompt);
  communicatorResult.retrievedContext = { runbooks: communicatorRunbooks };

  // Auto-retry loop: if patcher confidence < 0.70, re-run diagnoser with broader context
  let finalDiagnoserResult = diagnoserResult;
  let finalPatcherResult = patcherResult;
  let retryCount = 0;
  const maxRetries = 2;
  
  while ((!finalPatcherResult.confidence || finalPatcherResult.confidence < 0.70) && retryCount < maxRetries) {
    console.log(`Patch confidence ${finalPatcherResult.confidence || 'unknown'} below threshold, retrying diagnosis (attempt ${retryCount + 1}/${maxRetries})`);
    retryCount++;
    
    // Re-run diagnoser with broader context (more RAG results)
    const { pastIncidents: retryIncidents, runbooks: retryRunbooks } = await getDiagnoserContext(
      incident.component || 'unknown',
      watcherResult.description || 'anomaly'
    );
    const retryRagContext = buildDiagnoserRagContext(retryIncidents, retryRunbooks);
    
    const retryPrompt = `
      Previous diagnosis had low patch confidence. Re-analyze with broader context.
      
      Watcher's analysis:
      ${JSON.stringify(watcherResult, null, 2)}

      Original metrics:
      ${JSON.stringify(incident.metrics, null, 2)}

      Incident description: ${incident.description}

      ${retryRagContext}

      Previous root cause: ${finalDiagnoserResult.rootCause}
      Previous patch confidence: ${finalPatcherResult.confidence || 'unknown'}

      Provide a more specific, actionable root cause for better patch generation.
    `;
    
    const retryDiagnoserResult = await callOllamaAPI(AGENTS.DIAGNOSER, retryPrompt);
    retryDiagnoserResult.retrievedContext = { pastIncidents: retryIncidents, runbooks: retryRunbooks };
    finalDiagnoserResult = retryDiagnoserResult;
    
    // Re-run patcher with improved diagnosis
    const { runbooks: retryPatcherRunbooks, patchCommands: retryPatchCommands } = await getPatcherContext(
      retryDiagnoserResult.rootCause || 'unknown issue',
      incident.component || 'service'
    );
    const retryPatcherRagContext = buildPatcherRagContext(retryPatcherRunbooks, retryPatchCommands);
    
    const retryPatcherPrompt = `
      Improved diagnosis:
      ${JSON.stringify(retryDiagnoserResult, null, 2)}

      ${retryPatcherRagContext}

      Generate a high-confidence fix for this issue.
    `;
    
    const retryPatcherResult = await callOllamaAPI(AGENTS.PATCHER, retryPatcherPrompt);
    retryPatcherResult.retrievedContext = { runbooks: retryPatcherRunbooks, patchCommands: retryPatchCommands };
    finalPatcherResult = retryPatcherResult;
  }
  
  if (retryCount > 0) {
    console.log(`Auto-retry completed after ${retryCount} iteration(s), final patch confidence: ${finalPatcherResult.confidence || 'unknown'}`);
  }

  // Step 6: External integrations (Slack + GitHub PR)
  const slackResult = await sendSlackNotification(incident, watcherResult, finalDiagnoserResult, finalPatcherResult, communicatorResult);
  const githubResult = await createGitHubPR(incident, finalPatcherResult, finalDiagnoserResult);

  // Step 7: Persist to Supabase
  const incidentWithTrigger = { ...incident, triggered_at: incident.triggered_at || incident.timestamp || new Date().toISOString() };
  const fullResult = {
    orchestrator: orchestratorResult,
    watcher: watcherResult,
    diagnoser: finalDiagnoserResult,
    patcher: finalPatcherResult,
    communicator: communicatorResult,
    slackNotification: slackResult,
    githubPR: githubResult,
    retryCount,
    status: 'completed'
  };
  
  await saveFullIncident(incidentWithTrigger, fullResult).catch(err => 
    console.error('Supabase persistence failed:', err.message)
  );

  return fullResult;
}

module.exports = { runAgentChain };
